---
title: "p8105_hw1_hq2182"
author: Hanfei Qi
output: github_document
---

This is my solution to HW1.

```{r}
library(tidyverse)
```


## Problem 1

Create a data frame with specific elements

```{r dataframe}
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_10 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
)
```

Take the mean of each variable in my data frame.

```{r}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_10))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, factor_vec))
```

I can take the mean of numbers and logical but not character or factor.

```{r}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_10))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

```{r}
as.numeric(pull(prob1_df, samp_gt_10)) * pull(prob1_df, samp)
as.factor(pull(prob1_df, samp_gt_10)) * pull(prob1_df, samp)
as.numeric(as.factor(pull(prob1_df, samp_gt_10))) * pull(prob1_df, samp)
```


## Problem 2